
image: gitpod/workspace-java-21

ports:
  - port: 9200
    visibility: public
  - port: 8080
    visibility: public
    onOpen: open-browser
  - port: 5050
    visibility: public
  - port: 3000
    visibility: public
    onOpen: open-browser

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - Pivotal.vscode-boot-dev-pack
