version: '3.7'
services:
    ollama:
        image: langchain4j/ollama-orca-mini:latest
        ports:
          - '11434:11434'
    redis-stack:
        image: redis/redis-stack-server
        ports:
          - '6379:6379'