spring.application.name=rag-react-springai-ollama

# Ollama Models configuration
spring.ai.ollama.init.pull-model-strategy=WHEN_MISSING
spring.ai.ollama.chat.model=mistral
spring.ai.ollama.chat.keep-alive=30m
spring.ai.ollama.chat.temperature=0.3
spring.ai.ollama.chat.top-k=2
spring.ai.ollama.chat.top-p=0.2

# Postgres Vector Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/vector_db
spring.datasource.username=myuser
spring.datasource.password=secretpassword

# Spring AI Vector Store Configuration
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1024
spring.ai.vectorstore.pgvector.initialize-schema=false

# Liquibase Configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

##Observability
spring.ai.chat.observations.log-completion=true
spring.ai.chat.observations.log-prompt=true
spring.ai.chat.client.observations.log-prompt=true
spring.ai.vectorstore.observations.log-query-response=true

management.endpoints.web.exposure.include=*
management.metrics.tags.service.name=${spring.application.name}
management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.otlp.metrics.export.step=30s

spring.http.clients.connect-timeout=PT1M
spring.http.clients.read-timeout=PT5M

spring.testcontainers.beans.startup=parallel
