services:

    ollama:
      container_name: ollama
      image: ollama/ollama:latest
      ports:
        - '11434:11434'

    postgresqldb:
        container_name: postgresqldb
        image: pgvector/pgvector:pg17
        extra_hosts: [ 'host.docker.internal:host-gateway' ]
        restart: always
        environment:
          - POSTGRES_USER=appuser
          - POSTGRES_PASSWORD=secret
          - POSTGRES_DB=appdb
          - PGPASSWORD=secret
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        healthcheck:
          test: "pg_isready -U appuser -d appdb"
          interval: 2s
          timeout: 20s
          retries: 10
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        extra_hosts: [ 'host.docker.internal:host-gateway' ]
        environment:
          PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
          PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
          PGADMIN_CONFIG_SERVER_MODE: "False"
          PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
        ports:
          - "${PGADMIN_PORT:-5050}:80"
        depends_on:
          postgresqldb:
            condition: service_healthy
        volumes:
          - ./docker_pgadmin_servers.json:/pgadmin4/servers.json
        entrypoint:
          - "/bin/sh"
          - "-c"
          - "/bin/echo 'postgresqldb:5432:*:appuser:secret' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"

    lgtm-stack:
      image: grafana/otel-lgtm:0.11.1
      extra_hosts: [ 'host.docker.internal:host-gateway' ]
      container_name: lgtm-stack
      environment:
        - OTEL_METRIC_EXPORT_INTERVAL=500
      ports:
        - "3000:3000"
        - "4317:4317"
        - "4318:4318"
        - "9090:9090"
