services:

    ollama:
      container_name: ollama
      image: ollama/ollama:latest
      ports:
        - '11434:11434'
    redis-stack:
      container_name: redis-stack
      image: redis/redis-stack:7.4.0-v1
      extra_hosts: [ 'host.docker.internal:host-gateway' ]
      restart: always
      ports:
        - '6379:6379'
        - '8001:8001'
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 2s
        timeout: 20s
        retries: 10

    lgtm-stack:
      image: grafana/otel-lgtm:0.28.0
      extra_hosts: [ 'host.docker.internal:host-gateway' ]
      container_name: lgtm-stack
      environment:
        - OTEL_METRIC_EXPORT_INTERVAL=500
      ports:
        - "3000:3000"
        - "4317:4317"
        - "4318:4318"
        - "9090:9090"
