spring.application.name=model-regression-detection

# Ollama Properties
spring.ai.ollama.base-url=${OLLAMA_BASE_URL:http://localhost:11434}
spring.ai.ollama.chat.model=llama3.2
spring.ai.ollama.chat.options.temperature=0.0

# Database Properties (PostgreSQL)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/evaldb}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# PGVector Properties
spring.ai.vectorstore.pgvector.initialize-schema=true

# SQL Init
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema.sql


# Observability
spring.ai.chat.observations.log-completion=true
spring.ai.chat.observations.log-prompt=true
spring.ai.chat.client.observations.log-prompt=true

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.tags.service.name=${spring.application.name}

# Custom Evaluation Thresholds
eval.thresholds.warning-delta-percent=3
eval.thresholds.critical-delta-percent=8
eval.thresholds.drift-threshold=0.85
