spring.application.name=chatmodel-springai

spring.threads.virtual.enabled=true

spring.ai.openai.api-key=demo
spring.ai.openai.base-url=http://langchain4j.dev/demo/openai/v1
spring.ai.openai.chat.temperature=0.7
spring.ai.openai.chat.model=gpt-4o-mini
spring.ai.openai.chat.responseFormat.type=json_schema
spring.ai.openai.embedding.model=text-embedding-3-small


##logging
logging.level.org.apache.hc.client5.http=INFO
