services:
    ollama:
        image: langchain4j/ollama-llama3:latest
        ports:
          - '11434:11434'
    redis-stack:
        image: redis/redis-stack-server
        ports:
          - '6379:6379'
    lgtm-stack:
        image: grafana/otel-lgtm:0.7.1
        extra_hosts: ['host.docker.internal:host-gateway']
        container_name: lgtm-stack
        environment:
          - OTEL_METRIC_EXPORT_INTERVAL=500
        ports:
          - "3000:3000"
          - "4317:4317"
          - "4318:4318"